model_params:
  architecture: "RACCOON"         # "RACCOON" or "PENGUIN"
  layer_param: 32                 # any integer 
  dropout: 0.75                   # any float between 0 and 1
  name: "long1"                # any string

data_params:
  datafile: "/mn/stornext/d10/data/johanmkr/simulations/data_z1/data_z1.h5"
  train_seeds: 1500
  test_seeds: 200
  newton_augmentation: 1.0

train_params:
  epochs: 10
  lr: 0.01
  log_dir: "longruns"
