model_params:
  architecture: "RACCOON"         # "RACCOON" or "PENGUIN"
  layer_param: 32                 # any integer 
  dropout: 0.5                    # any float between 0 and 1
  name: "Somename"                # any string

data_params:
  datafile: "/mn/stornext/d10/data/johanmkr/simulations/data_z1/data_z1.h5"
  train_seeds: 100
  test_seeds: 25
  newton_augmentation: 1.0

train_params:
  epochs: 5
  lr: 0.001
  log_dir: "cnn_storage/testruns"
