model_params:
  architecture: "RACCOON"         # "RACCOON" or "PENGUIN"
  layer_param: 16                 # any integer 
  dropout: 0.5                    # any float between 0 and 1
  name: "testing_amp_200s"                # any string

data_params:
  datafile: ""
  train_seeds: 150
  test_seeds: 50
  newton_augmentation: 1.0

train_params:
  epochs: 1000
  lr: 0.0001
  log_dir: "testing_amp/runs"