MODEL_NAME: "MOUSE"

# Data params
NUM_WORKERS: 4
NGRID: 256
STRIDE: 2
SEEDS: np.arange(0,2000,50)
REDSHIFTS: 1.0
AXES: [0]

# Training params
BATCH_SIZE: 32
NUM_EPOCHS: 100
LEARNING_RATE: 0.0001
TRAIN_TEST_VAL_SPLIT: [0.6, 0.2, 0.2]
SPLIT_SEED: 42

# Computer related
ACCELERATOR: "cpu"
PRECISION: 32
DEVICES: [0]

#Logging
LOG_DIR: "tb_logs"